// Generated by https://quicktype.io

export interface ContestResponse {
  status: number;
  error: boolean;
  msg: string;
  payload: Payload[];
}

export interface Payload {
  contest: Contest[];
  prizes?: any[];
  registeredUsers?: any[];
}

export interface Contest {
  _id?: string;
  name: string;
  status: boolean;
  rounds: number;
  contestDate: string;
  createdBy: CreatedBy;
  image: string;
  createdAt: string;
}
export interface CreatedBy {
  _id: string;
  name: string;
}
