// Generated by https://quicktype.io

export interface UserResponse {
  status:  number;
  error:   boolean;
  msg:     string;
  payload: Payload[];
}

export interface Payload {
  name:      string;
  email:     string;
  role:      string;
  status:    boolean;
  createdAt: string;
  uid:       string;
}